#!/usr/bin/env bash

USE_COLOR=0

if [[ -t 1 ]] && [[ "${TERM:-}" != "dumb" ]]; then
  if command -v tput >/dev/null 2>&1; then
    ncolors=$(tput colors)
    if [[ -n "$ncolors" ]] && [[ "$ncolors" -ge 8 ]]; then
      USE_COLOR=1
    fi
  fi
fi

if ((USE_COLOR)); then
  YELLOW="$(printf '\033[33m')"
  BLUE="$(printf '\033[34m')"
  GREEN="$(printf '\033[32m')"
  RED="$(printf '\033[31m')"
  BOLD="$(printf '\033[1m')"
  RESET="$(printf '\033[0m')"
else
  RED=''
  GREEN=''
  YELLOW=''
  BLUE=''
  BOLD=''
  RESET=''
fi

printMsg() {
  printf '\n%s%s>>> %s%s\n' "$BLUE" "$BOLD" "$1" "$RESET"
}

printDone() {
  printf '\n%s%s✔ %s%s\n' "$GREEN" "$BOLD" "$1" "$RESET"
}

printWarn() {
  printf '\n%s%s! %s%s\n' "$YELLOW" "$BOLD" "$1" "$RESET"
}

printError() {
  printf '\n%s%s✘ %s%s\n' "$RED" "$BOLD" "$1" "$RESET"
}

printEnd() {
  printf '\n%s%s::%s::%s\n' "$GREEN" "$BOLD" "$1" "$RESET"
}

preCheck() {
  if [[ ! -t 1 ]]; then
    if command -v alacritty >/dev/null; then
      exec alacritty -e bash "$0" "$@"
    elif command -v kitty >/dev/null; then
      exec kitty -e bash "$0" "$@"
    elif command -v konsole >/dev/null; then
      exec konsole -e bash "$0" "$@"
    elif command -v gnome-terminal >/dev/null; then
      exec gnome-terminal -- bash "$0" "$@"
    else
      echo "No terminal emulator found"
      exit 1
    fi
  fi

  if ! command -v pacman >/dev/null; then
    printWarn "Run only on systems with pacman as the package manager.\nIf you somehow managed to delete the \"pacman\" package then IDK.\n"
    printError "Press any key to EXIT"
    read -r
    exit 1
  fi
}

helptext() {
  printf '%sA package manager for Arch Based Systems using pacman, AUR and Flatpak repos. Supports "yay" and "paru" AUR helpers.%s\n' "$YELLOW" "$RESET"
  echo
  printf '    %s--help | -h%s       :         Shows the help menu (This menu)\n' "$BLUE" "$RESET"
  printf '    %s--update%s          :         Updates the system\n' "$BLUE" "$RESET"
  printf '    %s--updatecount%s     :         Shows the number of available updates\n' "$BLUE" "$RESET"
}

aurSetup() {
  forceAurHelperCacheReset="$1"
  aurDetect() {
    aurHelperCacheFile="${XDG_CACHE_HOME:-$HOME/.cache}/aurHelper"
    if [ "$forceAurHelperCacheReset" != "--forcereset" ]; then
      if [ -f "$aurHelperCacheFile" ]; then
        savedAURHelper=$(<"$aurHelperCacheFile")
        if command -v "$savedAURHelper" >/dev/null 2>&1; then
          aurHelper="$savedAURHelper"
          return
        fi
      fi
    fi

    aurHelpers=()
    command -v yay >/dev/null 2>&1 && aurHelpers+=("yay")
    command -v paru >/dev/null 2>&1 && aurHelpers+=("paru")

    if [ ${#aurHelpers[@]} -eq 0 ]; then
      aurHelper="None"
      echo "$aurHelper" >"$aurHelperCacheFile"
    elif [ ${#aurHelpers[@]} -eq 1 ]; then
      aurHelper="${aurHelpers[0]}"
      echo "$aurHelper" >"$aurHelperCacheFile"
    else
      aurHelpers+=("None")
      aurHelper=$(printf "%s\n" "${aurHelpers[@]}" |
        fzf --prompt="Select AUR Helper: " \
          --header="Choose which AUR helper to use. If you dont have a AUR helper choose \"None\"" \
          --preview-window=wrap \
          --preview '
                    echo "Hovered Option:";
                    echo {}
            ')
      [ -z "$aurHelper" ] && echo "No selection made. Exiting." && exit 1
      echo "$aurHelper" >"$aurHelperCacheFile"
    fi
  }

  aurArgs() {
    if [[ "$aurHelper" != "None" ]]; then
      if [[ "$aurHelper" = "yay" ]]; then
        aurHelperArgs=(--devel
          --needed
          --answerupgrade None
          --answerclean All
          --answerdiff None
          --noremovemake
          --redownload
          --rebuild
          --cleanafter
          --sudoloop
          --noconfirm
          --mflags
          --noconfirm)
        aurDevelDataGenArgs=(-Y --gendb)
        cleanPkgArgs=(-Scc)
      elif [[ "$aurHelper" = "paru" ]]; then
        aurHelperArgs=()
        aurDevelDataGenArgs=(--gendb)
        cleanPkgArgs=(-Sccd)
      fi
    fi
  }
  aurDetect
  aurArgs
}

inhibitSleep() {
  if command -v systemd-inhibit >/dev/null 2>&1; then
    printWarn "Inhibiting Sleep using \"systemd-inhibit\"."
    local who="$1"
    local why="$2"
    shift 2
    systemd-inhibit --what=idle:sleep \
      --who="$who" \
      --why="$why" \
      "$@"
  else
    printWarn "\"systemd-inhibit\" command not found. Unable to Inhibit Sleep."
    shift 2
    "$@"
  fi
}

continuePromptAnyKey() {
  printEnd "Press any key to Continue"
  {
    trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
    read -n1 -r
  }
  anyKeyPromptStatus=$?
  if [[ $anyKeyPromptStatus -eq 0 ]] || [[ $anyKeyPromptStatus -eq 130 ]]; then
    clear
    return
  fi
}

copyPkgNames() {
  if command -v wl-copy >/dev/null 2>&1; then
    echo "$@" | wl-copy 2>/dev/null && printDone "Copied Package Names to clipboard"
    echo "$@"
  elif command -v xclip >/dev/null 2>&1; then
    echo "$@" | xclip -selection clipboard 2>/dev/null && printDone "Copied Package Names to clipboard"
    echo "$@"
  else
    printError "\"wl-copy\" or \"xclip\" not found. Install either one to copy the Package Names.\n\nSelected Packages:"
    echo "$@"
  fi
}

installListedPkgs() {
  case "$selectedPkgType" in
  Pacman)
    printMsg "Installing Packages..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      inhibitSleep "Installing Package" \
        "Prevent shutdown/sleep during package installation" \
        sudo pacman -S --noconfirm "$@"
    }
    installStatus=$?
    ;;
  AUR)
    printMsg "Installing Packages..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      inhibitSleep "Installing Package" \
        "Prevent shutdown/sleep during package installation" \
        "$aurHelper" "${aurHelperArgs[@]}" -S "$@"
    }
    installStatus=$?
    ;;
  Flatpak)
    printMsg "Installing Packages..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      local entry app repo _
      for entry in "$@"; do
        read -r app repo _ <<<"$entry"
        inhibitSleep "Installing Package" \
          "Prevent shutdown/sleep during package installation" \
          flatpak install --assumeyes "$repo" "$app"
      done
    }
    installStatus=$?
    ;;
  esac

  if [[ $installStatus -eq 0 ]]; then
    printDone "Successfully Installed Packages"
  elif [[ $installStatus -eq 130 ]]; then
    printError "Package Install interrupted"
  else
    printError "Failed to Install Packages"
  fi
  continuePromptAnyKey
}

uninstallListedPkgs() {
  case "$selectedPkgType" in
  Pacman)
    printMsg "Uninstalling Packages..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      inhibitSleep "Installing Package" \
        "Prevent shutdown/sleep during package installation" \
        sudo pacman -Rns --noconfirm "$@"
    }
    uninstallStatus=$?
    ;;
  AUR)
    printMsg "Uninstalling Packages..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      inhibitSleep "Uninstalling Package" \
        "Prevent shutdown/sleep during package Uninstallation" \
        "$aurHelper" -Rns --noconfirm "$@"
    }
    uninstallStatus=$?
    ;;
  Flatpak)
    printMsg "Uninstalling Packages..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      flatpakUninstallSuccessPkgNames=()
      flatpakUninstallFailedPkgNames=()

      for flatpakUninstallPkgNames in "$@"; do
        [[ -z "$flatpakUninstallPkgNames" ]] && continue
        printMsg "Uninstalling $flatpakUninstallPkgNames..."
        inhibitSleep "Installing Package" \
          "Prevent shutdown/sleep during package installation" \
          flatpak uninstall --assumeyes "$flatpakUninstallPkgNames"
        flatpakUninstallStatus=$?
        if [[ $flatpakUninstallStatus -eq 0 ]]; then
          printDone "$flatpakUninstallPkgNames uninstalled successfully"
          flatpakUninstallSuccessPkgNames+=("$flatpakUninstallPkgNames")
        else
          printError "Failed to uninstall $flatpakUninstallPkgNames"
          flatpakUninstallFailedPkgNames+=("$flatpakUninstallPkgNames")
        fi
      done

      if ((${#flatpakUninstallSuccessPkgNames[@]})); then
        for flatpakUninstallSuccessPkgName in "${flatpakUninstallSuccessPkgNames[@]}"; do
          flatpakDataDir="$HOME/.var/app/$flatpakUninstallSuccessPkgName"
          if [[ -d "$flatpakDataDir" ]]; then
            printWarn "App data found for $flatpakUninstallSuccessPkgName"
            printMsg "Do you want to remove app data for '$flatpakUninstallSuccessPkgName'? (y/N): "
            read -r ans </dev/tty
            if [[ "$ans" =~ ^[Yy]$ ]]; then
              echo "Deleting app data: $flatpakDataDir"
              rm -rfv -- "$flatpakDataDir"
              printDone "App data removed for $flatpakUninstallSuccessPkgName"
            else
              printMsg "App data retained for $flatpakUninstallSuccessPkgName"
            fi
          else
            printWarn "No app data found for $flatpakUninstallSuccessPkgName"
          fi
        done
      fi
    }
    uninstallStatus=$?
    ;;
  esac

  if [[ $uninstallStatus -eq 0 ]]; then
    printDone "Successfully Uninstalled Packages"
  elif [[ $uninstallStatus -eq 130 ]]; then
    if [[ -n $flatpak_failed_uninstallStatus ]]; then
      printError "Package Uninstall interrupted.. Failed to Uninstall ${flatpakUninstallFailedPkgNames[*]}"
    else
      printError "Package Uninstall interrupted"
    fi
  else
    if [[ -n $flatpak_failed_uninstallStatus ]]; then
      printError "Failed to Uninstall ${flatpakUninstallFailedPkgNames[*]}"
    else
      printError "Failed to Uninstall Packages"
    fi
  fi
  continuePromptAnyKey
}

whichPkgType() {
  case "$aurHelper" in
  "None")
    pkgTypeChoices="Pacman"
    ;;
  *)
    pkgTypeChoices="Pacman\nAUR"
    ;;
  esac

  command -v flatpak >/dev/null && pkgTypeChoices="${pkgTypeChoices}\nFlatpak"
  pkgTypeChoices="${pkgTypeChoices}\nBack"

  selectedPkgType=$(printf "%b" "$pkgTypeChoices" |
    fzf --prompt="Search: " \
      --header="Select package type: " \
      --preview-window=wrap \
      --preview '
                    if [[ {} = "Back" ]]; then
                        echo "↩ Return to previous menu"
                    else
                        echo "Hovered Option:";
                        echo {}
                    fi
            ')
}

listRemotePkgs() {
  while true; do

    whichPkgType

    [ -z "$selectedPkgType" ] && return

    case "$selectedPkgType" in
    Pacman)
      listRemotePkgCmd="pacman -Slq"
      fzfPreviewRemotePkgs='
                            if pacman -Qin {1} &>/dev/null; then
                                echo "*****Installed*****"
                                echo
                                pacman -Qin {1};
                            else
                                pacman -Si {1};
                            fi
                '
      ;;
    AUR)
      listRemotePkgCmd="$aurHelper -Slqa"
      fzfPreviewRemotePkgs='
                            if '"$aurHelper"' -Qim {1} &>/dev/null; then
                                echo "*****Installed*****"
                                echo
                                '"$aurHelper"' -Qim {1} || pacman -Qim {1};
                            else
                                '"$aurHelper"' -Si {1};
                            fi
                '
      ;;
    Flatpak)
      listRemotePkgCmd="flatpak search --columns=application,remote,branch \"\""
      fzfPreviewRemotePkgs='
                            if flatpak info {1} &>/dev/null; then
                                echo "*****Installed*****"
                                echo
                                flatpak info {1}
                            else
                                flatpak remote-info {2} {1}/x86_64/{3} --system 2>/dev/null || flatpak remote-info {2} {1}/x86_64/{3} --user
                            fi
                '
      ;;
    Back)
      return
      ;;
    esac
    local selectedPkgNames
    selectedPkgNames=$({
      printf "Back\n"
      {
        eval "$listRemotePkgCmd" 2>/dev/null &
      }
    } |
      fzf --multi \
        --prompt="Search Packages: " \
        --header="Use TAB to select, ENTER to Install." \
        --preview-window=wrap \
        --preview '
                    if [[ {} = "Back" ]]; then
                        echo "↩ Return to previous menu"
                    else
                        echo "Selected Packages:";
                        echo {+} | tr " " "\n";
                        echo;
                        echo "Hovered Packages:";
                        echo {} | tr " " "\n";
                        echo;
                        '"$fzfPreviewRemotePkgs"'
                    fi
        ')
    [ -z "$selectedPkgNames" ] && continue
    case "$selectedPkgNames" in
    "Back")
      continue
      ;;
    *)
      mapfile -t installPkgNames <<<"$selectedPkgNames"
      installListedPkgs "${installPkgNames[@]}"
      return
      ;;
    esac
  done
}

listInstalledPkgs() {
  while true; do

    whichPkgType

    [ -z "$selectedPkgType" ] && return

    case "$selectedPkgType" in
    Pacman)
      listInstalledPkgCmd="pacman -Qqn"
      fzfPreviewInstalledPkgs='pacman -Qin {1}'
      ;;
    AUR)
      listInstalledPkgCmd="$aurHelper -Qqm"
      fzfPreviewInstalledPkgs="$aurHelper -Qim {1} || pacman -Qim {1}"
      ;;
    Flatpak)
      listInstalledPkgCmd="flatpak list --columns=application --app | grep -v \"Application ID\""
      fzfPreviewInstalledPkgs='flatpak info {1}'
      ;;
    Back)
      return
      ;;
    esac
    local selectedPkgNames
    selectedPkgNames=$({
      printf "Back\n"
      eval "$listInstalledPkgCmd"
    } |
      fzf --multi \
        --prompt="Search Packages: " \
        --header="Use TAB to select, ENTER to Uninstall." \
        --preview-window=wrap \
        --preview '
                    if [[ {} = "Back" ]]; then
                        echo "↩ Return to previous menu"
                    else
                        echo "Selected Packages:";
                        echo {+} | tr " " "\n";
                        echo;
                        echo "Hovered Packages:";
                        echo {} | tr " " "\n";
                        echo;
                        '"$fzfPreviewInstalledPkgs"'
                    fi
        ')
    [ -z "$selectedPkgNames" ] && continue
    case "$selectedPkgNames" in
    "Back") continue ;;
    *)
      mapfile -t uninstallPkgNames <<<"$selectedPkgNames"
      uninstallListedPkgs "${uninstallPkgNames[@]}"
      return
      ;;
    esac
  done
}

cleanup() {
  local pid=${1:-$$}
  local children
  children=$(pgrep -P "$pid" 2>/dev/null)
  for child in $children; do
    cleanup "$child"
  done
  # Kill the process itself, but never the script's main PID
  if [[ "$pid" != "$$" ]]; then
    kill -9 "$pid" 2>/dev/null
  fi
}

checkUpdateList() {
  trap 'cleanup; echo "Ctrl+C pressed, update checks stopped."; return 130' INT

  local updatePkgList
  updatePkgList=$(mktemp -u)
  mkfifo "$updatePkgList"

  if [[ "${1}" == "fzf" ]]; then
    echo "Back" >>"$updatePkgList" &
  fi

  { checkupdates 2>/dev/null | sed 's/\x1b\[[0-9;]*m//g' >>"$updatePkgList"; } &

  if [ "$aurHelper" != "None" ]; then
    { "$aurHelper" -Qua --devel 2>/dev/null | grep -vF "devel check for package failed" >>"$updatePkgList"; } &
  fi

  if command -v flatpak >/dev/null; then
    { flatpak remote-ls --updates --columns=application,version 2>/dev/null | grep -v "Application ID" >>"$updatePkgList"; } &
  fi

  "$@" <"$updatePkgList"
  local cmdStatus=$?
  cleanup
  rm -f "$updatePkgList"
  return $cmdStatus
}

pkgUpdateCount() {
  checkUpdateList wc -l
}

listUpdatePkgs() {
  while true; do
    case "$aurHelper" in
    "None")
      command -v flatpak >/dev/null && fzfPreviewUpdateListInfo="pacman -Si {1} || flatpak info {1}" || fzfPreviewUpdateListInfo="pacman -Si {1}"
      ;;
    *)
      command -v flatpak >/dev/null && fzfPreviewUpdateListInfo="$aurHelper -Si {1} || flatpak info {1}" || fzfPreviewUpdateListInfo="$aurHelper -Si {1}"
      ;;
    esac

    local selectedPkgNames
    selectedPkgNames=$(checkUpdateList fzf --multi \
      --prompt="Search Packages: " \
      --header="Use TAB to select, ENTER to Update All Packages." \
      --preview-window=wrap \
      --preview '
            if [[ {} = "Back" ]]; then
                echo "↩ Return to previous menu"
            else
                '"$fzfPreviewUpdateListInfo"'
            fi
        ')

    [ -z "$selectedPkgNames" ] && return

    case "$selectedPkgNames" in
    "Back")
      return
      ;;
    *)
      updatePkgs
      return
      ;;
    esac
  done
}

updatePkgs() {
  updateArchPkgs() {
    printMsg "Updating Arch repo packages with \"sudo pacman -Syu\"..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      inhibitSleep "System Update" "Prevent shutdown/sleep during system upgrade" \
        sudo pacman -Syu --noconfirm
    }
    pacmanUpdateStatus=$?
  }
  updateAURPkgs() {
    printMsg "Updating AUR packages with \"$aurHelper ${aurHelperArgs[*]} -Syua\"..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      inhibitSleep "System Update" "Prevent shutdown/sleep during system upgrade" \
        "$aurHelper" "${aurHelperArgs[@]}" -Syua
    }
    AURUpdateStatus=$?
  }
  updateFlatpakPkgs() {
    printMsg "Updating Flatpak packages with \"flatpak update --assumeyes\"..."
    {
      trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
      inhibitSleep "System Update" "Prevent shutdown/sleep during system upgrade" \
        flatpak update --assumeyes
    }
    flatpakUpdateStatus=$?
  }

  printUpdateStatus() {
    printWarn "------------------------------------------------------------------------- !"
    if [[ $pacmanUpdateStatus -eq 0 ]]; then
      printDone "Arch repo packages updated"
    elif [[ $pacmanUpdateStatus -eq 130 ]]; then
      printError "Arch repo update interrupted"
    else
      printError "Failed to update Arch repo packages"
    fi

    if [[ "$aurHelper" != "None" ]]; then
      if [[ $AURUpdateStatus -eq 0 ]]; then
        printDone "AUR packages updated"
      elif [[ $AURUpdateStatus -eq 130 ]]; then
        printError "AUR update interrupted"
      else
        printError "Failed to update AUR packages"
      fi
    fi

    if command -v flatpak >/dev/null; then
      if [[ $flatpakUpdateStatus -eq 0 ]]; then
        printDone "Flatpak packages updated"
      elif [[ $flatpakUpdateStatus -eq 130 ]]; then
        printError "Flatpak update interrupted"
      else
        printError "Failed to update Flatpak packages"
      fi
    fi
    printWarn "------------------------------------------------------------------------- !"
  }

  mainupdate() {
    updateArchPkgs
    if [[ "$aurHelper" != "None" ]]; then
      updateAURPkgs
    fi
    if command -v flatpak >/dev/null; then
      updateFlatpakPkgs
    fi
    printUpdateStatus
    continuePromptAnyKey
  }

  mainupdate
}

generateAURDevelData() {
  printMsg "Generating data for Devel Packages eg:- \"-git\" Packages"
  {
    trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
    "$aurHelper" "${aurDevelDataGenArgs[@]}"
  }
  continuePromptAnyKey
  return
}

cheanPkgCache() {
  printMsg "Cleaning Package Cache"
  {
    trap 'pkill sudo; echo Ctrl+C pressed; return 130' INT
    sudo rm -rfv -- /var/cache/pacman/pkg/download-*
    if [[ "$aurHelper" = "None" ]]; then
      yes | sudo pacman -Scc
    else
      yes | "$aurHelper" "${cleanPkgArgs[@]}"
    fi
    if command -v flatpak >/dev/null; then
      flatpak uninstall --unused
    fi
  }
  continuePromptAnyKey
  return
}

listOrphanPkgs() {
  local selectedPkgNames
  selectedPkgNames=$({
    printf "Back\n"
    pacman -Qdtq
  } |
    fzf --multi \
      --prompt="Search Packages: " \
      --header="Use TAB to select, ENTER to Uninstall." \
      --preview-window=wrap \
      --preview '
            if [[ {} = "Back" ]]; then
                echo "↩ Return to previous menu"
            else
                echo "Selected Packages:";
                echo {+} | tr " " "\n";
                echo;
                echo "Hovered Packages:";
                echo {} | tr " " "\n";
                echo;
                pacman -Qi {1}
            fi
    ')
  [ -z "$selectedPkgNames" ] && return
  case "$selectedPkgNames" in
  "Back") return ;;
  *)
    mapfile -t orphanPkg <<<"$selectedPkgNames"
    selectedPkgType="Pacman" && uninstallListedPkgs "${orphanPkg[@]}"
    return
    ;;
  esac
}

checkMissingPkgFromGroup() {
  listPkgGroups=$({
    pacman -Qg | awk '!seen[$1]++ { print $1 }'
  } |
    fzf \
      --prompt="Search Package Group: " \
      --header="Press ENTER View Not Installed Packages From the Selected Group." \
      --preview-window=wrap \
      --preview '
          if [[ {} = "Back" ]]; then
              echo "↩ Return to previous menu"
          else
              echo "Hovered Package Group:";
              echo {} | tr " " "\n";
          fi
    ')

  local selectedPkgNames
  selectedPkgNames=$({
    comm -23 <(pacman -Sg "$listPkgGroups" | awk '{print $2}' | sort) <(pacman -Qq | sort)
  } |
    fzf --multi \
      --prompt="Search Packages: " \
      --header="Use TAB to select, ENTER to Install." \
      --preview-window=wrap \
      --preview '
          if [[ {} = "Back" ]]; then
              echo "↩ Return to previous menu"
          else
              echo "Selected Packages:";
              echo {+} | tr " " "\n";
              echo;
              echo "Hovered Packages:";
              echo {} | tr " " "\n";
              echo;
              pacman -Si {1}
          fi
  ')
  [ -z "$selectedPkgNames" ] && return
  case "$selectedPkgNames" in
  "Back") return ;;
  *)
    mapfile -t missingPkgNames <<<"$selectedPkgNames"
    selectedPkgType="Pacman" && installListedPkgs "${missingPkgNames[@]}"
    return
    ;;
  esac
}

pkgMenu() {
  while true; do
    pkgManager=$(
      {
        printf "Install Packages\n"
        printf "Uninstall Packages\n"
        printf "Check Updates\n"
        printf "Update System\n"
        printf "Check Missing Package From Package Group\n"
        printf "List Orphan Packages\n"
        printf "Clean Package Cache\n"
        if [[ "$aurHelper" != "None" ]]; then
          printf "Generate devel Data For AUR Helpers\n"
        fi
        printf "Change AUR Helper\n"
        printf "Exit"
      } |
        fzf --prompt="Search: " \
          --header="Select Operation: " \
          --preview-window=wrap \
          --preview '
                printf '"'AUR Helper = %s\n'"' '"$aurHelper"'
                if [[ '"$aurHelper"' = "None" ]]; then
                  echo "\nPacman-only mode"
                fi
                echo;
                echo "Hovered Option:";
                echo {};
                echo;
                if [[ {} = "Exit" ]]; then
                  echo "↩ Exit the Manager"
                fi
        '
    )
    [ -z "$pkgManager" ] && return
    case "$pkgManager" in
    "Install Packages") listRemotePkgs ;;
    "Uninstall Packages") listInstalledPkgs ;;
    "Check Updates") listUpdatePkgs ;;
    "Update System") updatePkgs ;;
    "Check Missing Package From Package Group") checkMissingPkgFromGroup ;;
    "List Orphan Packages") listOrphanPkgs ;;
    "Clean Packages") cheanPkgCache ;;
    "Generate Devel Data For AUR Helpers") generateAURDevelData ;;
    "Change AUR Helper") aurSetup --forcereset && continue ;;
    "Exit") break ;;
    esac
  done
}

case "$1" in
"--help" | "-h")
  preCheck "$@"
  helptext
  ;;
"--update")
  preCheck "$@"
  aurSetup
  updatePkgs
  ;;
"--listupdates")
  preCheck "$@"
  aurSetup
  listUpdatePkgs
  ;;
"--updatecount")
  aurSetup
  pkgUpdateCount
  ;;
*)
  preCheck "$@"
  aurSetup
  pkgMenu
  ;;
esac
