post_install() {
  echo -e "\n==>Reloading keyd to apply changes..."
  sudo keyd reload 2>/dev/null && echo -e "Successfully reloaded keyd" || echo -e "keyd is not running, skipping reload"
  echo -e "\n====>>>>If your mouse is faster after using keyd then go to your mouse settings and change the keyd-virtual-pointer settings to be same as your current mouse settings.<<<<====\n"
}

post_remove() {
  post_install "$@"
}

post_upgrade() {
  post_install "$@"
}